config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "impressions#index"

  devise_scope :user do
    patch 'users/switch_show_name', to: 'users/registrations#switch_show_name'
    get 'users/two_factor_auth', to: 'users/sessions#two_factor_auth'
  end

  resources :creators, only: %i[index show] do
    resources :articles, only: %i[show], module: :creators
  end
  namespace :impressions do
    resources :tags, only: %i[index update destroy]
  end
  resources :impressions, only: %i[index show]
  resources :articles, only: %i[show]

  namespace :my_page do
    resources :impressions do
      collection do
        post :update_article
        get :download
      end
      member do
        patch :publish
        post :post_mastodon
      end
    end
    resources :impression_tags, only: %i[index new create destroy] do
      collection do
        post :show_all_tags
        post :add_tag
      end
    end
    resources :two_step_verifications, only: %i[new create]
    resources :tag_groups do
      member do
        get :edit_tags
        post :add_tag
        delete :destroy_tag
      end
    end
  end

  namespace :admin do
    resources :users
    resources :articles, only: %i[index show edit update] do
      member do
        get :reset
      end
    end
    resources :impressions, only: %i[index show destroy]
    resources :musics, except: :destroy
    resources :creators, except: :destroy
    resource :mastodon_data_linkage do
      collection do
        get :callback
      end
    end

    namespace :shared do
      resources :musics, except: %i[edit] do
        collection do
          post :show_music
        end
      end
      resources :creators, except: %i[edit]
    end
  end

  namespace :notices do
    resources :zakkuri_festival, only: %i[index]
  end
end

app/models/tag_group.rb
# == Schema Information
#
# Table name: tag_groups
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  sort_order :integer          default(0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tag_groups_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class TagGroup < ApplicationRecord
  belongs_to :user, inverse_of: :tag_groups
  has_many :tag_group_tags, dependent: :destroy, inverse_of: :tag_group
  has_many :tags, through: :tag_group_tags, inverse_of: :tag_groups

  scope :by_user, ->(user_id) { where(user_id: user_id) }

  def add_tag(tag_id)
    tag = Tag.find(tag_id)
    TagGroupTag.where(user: self.user, tag_id: tag.id).destroy_all
    self.tag_group_tags.create!(tag_id: tag.id, user: self.user)
  end
end

app/controllers/my_page/application_controller.rb
module MyPage
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/my_page/impression_tags_controller.rb
module MyPage
  class ImpressionTagsController < ApplicationController
    before_action :set_impression
    before_action :set_impression_tags, only: %i[index new destroy add_tag show_all_tags]
    before_action :set_impression_tag, only: %i[destroy]

    def index; end

    def new; end

    def create
      ActiveRecord::Base.transaction do
        @impression.create_tags!(params[:new_tags][:new_tags])
      end
      set_impression_tags
    end

    def destroy
      @impression_tag.destroy!
      set_impression_tags

      render :create
    end

    def add_tag
      ActiveRecord::Base.transaction do
        tag = Tag.find(params[:tag_id])
        @impression.add_tag!(tag)
      end
      set_impression_tags

      render :create
    end

    def show_all_tags
      @tags = @tags.content_like(params[:keyword]) if params[:keyword].present?
      set_tag_group
    end

    private def set_impression
      @impression = Impression.where(user: current_user).find(params[:impression_id])
    end

    private def set_impression_tag
      @impression_tag = @impression_tags.find(params[:id])
    end

    private def set_impression_tags
      @impression_tags = @impression.impression_tags.preload(:tag)
      @tags = Tag.where.not(id: @impression_tags.select(:tag_id)).order_by_count(current_user.id)
      set_tag_group
    end

    private def set_tag_group
      tag_id_by_group = TagGroupTag.where(user: current_user, tag_id: @tags.select(:id)).group(:tag_group_id).pluck(:tag_group_id, Arel.sql("ARRAY_AGG(tag_id)"))
      @tag_id_by_group = @tags.group_by { |tag| (tag_id_by_group.find { |_, tag_ids| tag_ids.include?(tag.id) } || [])[0] }
      @tag_groups = TagGroup.joins(:tag_group_tags).merge(TagGroupTag.where(tag_id: @tags.select(:id))).where(user: current_user).index_by(&:id)
    end
  end
end

app/controllers/my_page/impressions_controller.rb
module MyPage
  class ImpressionsController < ApplicationController
    before_action :set_impressions, except: %i[new create]
    before_action :set_impression, only: %i[show edit update update_temporary destroy publish post_mastodon]

    def index
      @impressions = @impressions.where(status: params[:status])
      @impressions = @impressions.page(params[:page]).per(5)
    end

    def new
      @impression = Impression.new
    end

    def show
      @decorated_impression = ImpressionDecorator.decorate(@impression)
      @impression_tags = @decorated_impression.impression_tags.preload(:tag)
    end

    def edit; end

    def update
      @impression.attributes = impression_params
      @impression.user = current_user
      if @impression.save
        message = @impression.pending? ? "下書きを保存しました" : "更新しました"
        redirect_to my_page_impressions_url(status: @impression.status), notice: message
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def create
      @impression = Impression.new(impression_params)
      @impression.user = current_user
      if @impression.save
        message = @impression.pending? ? "下書きを保存しました" : "登録しました"
        redirect_to my_page_impressions_url(status: @impression.status), notice: message
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update_article
      @article = Article.find_or_initialize_by_url(params[:url])
      @article.save if @article.present? && @article.valid?
    end

    def publish
      @impression.published!
      redirect_to my_page_impressions_url(status: :published)
    end

    def destroy
      @impression.destroy!
      redirect_to my_page_impressions_url, notice: "削除しました"
    end

    def post_mastodon
      @decorated_impression = ImpressionDecorator.decorate(@impression)
      Faraday.post("#{current_user.mastodon_data_linkage.site}/api/v1/statuses",
                   @decorated_impression.for_mastodon,
                   {
                     'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
                     'Authorization': "Bearer #{current_user.mastodon_data_linkage.token}"
                   })
    end

    def download
      send_data(
        Impression.to_csv,
        type: 'text/csv',
        filename: "download.csv"
      )
    end

    private

      def set_impression
        @impression = @impressions.find(params[:id])
      end

      def set_impressions
        @impressions = Impression.preload(:article, :tags).where(user: current_user).order(created_at: :desc, id: :asc)
      end

      def impression_params
        params.require(:impression).permit(:detail, :summary, :article_id, :entry_type)
      end
  end
end

app/controllers/my_page/tag_groups_controller.rb
module MyPage
  class TagGroupsController < ApplicationController
    before_action :set_tag_group, only: %i[show edit update destroy edit_tags add_tag destroy_tag]

    def index
      @tag_groups = TagGroup.by_user(current_user.id).page(params[:page])
    end

    def new
      @tag_group = TagGroup.new(user: current_user)
    end

    def show; end

    def edit; end

    def edit_tags
      set_used_tags
    end

    def update
      @tag_group.attributes = tag_group_params
      if @tag_group.save
        redirect_to my_page_tag_group_url(@tag_group), notice: "tag_group was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def create
      @tag_group = TagGroup.new(tag_group_params.merge(user: current_user))
      if @tag_group.save
        redirect_to my_page_tag_group_url(@tag_group), notice: "tag_group was successfully updated."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def add_tag
      ActiveRecord::Base.transaction do
        @tag_group.add_tag(params[:tag_id])
      end
      set_used_tags
    end

    def destroy_tag
      @tag_group.tag_group_tags.where(tag_id: params[:tag_id]).destroy_all
      set_used_tags

      render :add_tag
    end

    private
      def set_tag_group
        @tag_group = TagGroup.by_user(current_user.id).find(params[:id])
      end

      def tag_group_params
        params.require(:tag_group).permit(:name, :sort_order)
      end

      def set_used_tags
        @unused_tags = Tag.unused_tags(current_user.id)
        @other_tags = Tag.used_tags(current_user.id).where.not(id: @tag_group.tag_group_tags.select(:tag_id))
      end
  end
end

app/controllers/my_page/two_step_verifications_controller.rb
module MyPage
  class TwoStepVerificationsController < ApplicationController
    def new
      issuer = 'YourAppName'
      label = "#{issuer}:#{current_user.email}"

      uri = current_user.otp_provisioning_uri(label, issuer: issuer)

      @qr_code = RQRCode::QRCode.new(uri)
                                .as_png(resize_exactly_to: 200)
                                .to_data_url
    end

    def create
      if current_user.otp_required_for_login
        current_user.otp_required_for_login = false
      else
        unless current_user.validate_and_consume_otp!(params[:otp_attempt])
          flash[:notice] = "認証できませんでした"
          redirect_to new_my_page_two_step_verification_url
          return
        end
        current_user.otp_required_for_login = true
      end
      current_user.save!

      flash[:notice] = "変更しました"
      redirect_to root_url
    end
  end
end

app/views/my_page/tag_groups/_form.html.erb
<%= form_with(model: [:my_page, tag_group], html: { data: { controller: "form" } }) do |form| %>
  <% if tag_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag_group.errors.count, "error") %> prohibited this tag_group from being saved:</h2>

      <ul>
        <% tag_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.label :name, '名前', class: 'input-group-text' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :sort_order, '表示順', class: 'input-group-text' %>
    <%= form.number_field :sort_order, class: 'form-control', required: true %>
  </div>

  <div class="text-center mt-1">
    <%= form.submit '登録する', class: 'btn btn-primary btn-sm me-3' %>
  </div>
<% end %>

app/views/my_page/tag_groups/_tag_group.html.erb
<div id="<%= dom_id tag_group %>" class="js-impression">
  <div class="card m-2">
    <div class="card-header"><%= tag_group.name %></div>
    <div class="card-body">
      <div id="used_tags" class="d-flex flex-wrap">
        <%= render partial: "used_tags", locals: { tag_group: tag_group }  %>
      </div>
    </div>
    <div class="card-footer">
      表示順: <%= tag_group.sort_order %>
    </div>
  </div>
</div>

app/views/my_page/tag_groups/_tags.html.erb
<div class="js-impression mt-2">
  未使用タグ
  <div class="d-flex flex-wrap">
    <% unused_tags.each do |tag| %>
        <%= link_to tag.content, add_tag_my_page_tag_group_path(tag_group.id, tag_id: tag.id), data: { turbo_method: :post }, class: 'btn btn-sm btn-primary m-1' %>
    <% end %>
  </div>

  他グループ設定済み
  <div class="d-flex flex-wrap">
    <% other_tags.each do |tag| %>
      <%= link_to tag.content, add_tag_my_page_tag_group_path(tag_group.id, tag_id: tag.id), data: { turbo_method: :post }, class: 'btn btn-sm btn-primary m-1' %>
    <% end %>
  </div>
</div>

app/views/my_page/tag_groups/_used_tags.html.erb
<% tag_group.tags.each do |tag| %>
  <%= link_to "#{tag.content}×", destroy_tag_my_page_tag_group_path(tag_group, tag_id: tag.id),
              data: { turbo_method: :delete }, class: "btn btn-sm btn-outline-secondary m-1" %>
<% end %>

app/views/my_page/tag_groups/add_tag.turbo_stream.erb
<%= turbo_stream.update "used_tags", partial: 'used_tags', locals: { tag_group: @tag_group } %>
<%= turbo_stream.update "unused_tags", partial: 'tags', locals: { unused_tags: @unused_tags, other_tags: @other_tags, tag_group: @tag_group } %>

app/views/my_page/tag_groups/edit.html.erb
<div class="container js-impression" >
  <%= link_to "一覧に戻る", my_page_tag_groups_path, class: 'btn btn-outline-secondary btn-sm mb-3' %>

  <%= render partial: 'form', locals: { tag_group: @tag_group } %>
</div>

app/views/my_page/tag_groups/edit_tags.html.erb
<div class="container js-impression" >
  <p style="color: green"><%= notice %></p>

  <%= link_to "一覧に戻る", my_page_tag_groups_path, class: 'btn btn-outline-secondary btn-sm mb-3' %>
  <%= render @tag_group %>

  <div id="unused_tags">
    <%= render 'my_page/tag_groups/tags', unused_tags: @unused_tags, other_tags: @other_tags, tag_group: @tag_group %>
  </div>
</div>

app/views/my_page/tag_groups/index.html.erb
<div class="container js-impression" >
  <%= link_to '新規', new_my_page_tag_group_path, class: 'btn btn-outline-primary btn-sm mb-3' %>
  <div id="tag_groups">
    <div class="row py-3 border">
      <div class="col-6 fw-bolder">名前</div>
      <div class="col-6 fw-bolder">表示順</div>
    </div>

    <% @tag_groups.each do |tag_group| %>
      <div class="row py-3 border" id="<%= dom_id tag_group %>">
        <div class="col-6">
          <%= link_to tag_group.name, my_page_tag_group_path(tag_group), class: 'link-dark' %>
        </div>
        <div class="col-6">
          <%= tag_group.sort_order %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex border" >
    <%= paginate @tag_groups %>
  </div>
</div>

app/views/my_page/tag_groups/new.html.erb
<div class="container js-impression" >
  <%= link_to "一覧に戻る", my_page_tag_groups_path, class: 'btn btn-outline-secondary btn-sm mb-3' %>

  <%= render partial: 'form', locals: { tag_group: @tag_group } %>
</div>

app/views/my_page/tag_groups/show.html.erb
<div class="container js-impression" >
  <p style="color: green"><%= notice %></p>

  <%= link_to "一覧に戻る", my_page_tag_groups_path, class: 'btn btn-outline-secondary btn-sm mb-3' %>
  <%= render @tag_group %>

  <div class="text-center mt-1">
    <%= link_to "タグ編集", edit_tags_my_page_tag_group_path(@tag_group), class: 'btn btn-sm btn-outline-primary' %>
    <%= link_to "編集", edit_my_page_tag_group_path(@tag_group), class: 'btn btn-sm btn-outline-primary' %>
  </div>
</div>