config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "impressions#index"

  devise_scope :user do
    patch 'users/switch_show_name', to: 'users/registrations#switch_show_name'
    get 'users/two_factor_auth', to: 'users/sessions#two_factor_auth'
  end

  resources :creators, only: %i[index show] do
    resources :articles, only: %i[show], module: :creators
  end
  namespace :impressions do
    resources :tags, only: %i[index update destroy]
  end
  resources :impressions, only: %i[index show]
  resources :articles, only: %i[show]

  namespace :my_page do
    resources :impressions do
      collection do
        post :update_article
        get :download
      end
      member do
        patch :publish
        post :post_mastodon
      end
    end
    resources :impression_tags, only: %i[index new create destroy] do
      collection do
        post :show_all_tags
        post :add_tag
      end
    end
    resources :two_step_verifications, only: %i[new create]
    resources :tag_groups do
      member do
        get :edit_tags
        post :add_tag
        delete :destroy_tag
      end
    end
  end

  namespace :admin do
    resources :users
    resources :articles, only: %i[index show edit update] do
      member do
        get :reset
      end
    end
    resources :impressions, only: %i[index show destroy]
    resources :musics, except: :destroy
    resources :creators, except: :destroy
    resource :mastodon_data_linkage do
      collection do
        get :callback
      end
    end

    namespace :shared do
      resources :musics, except: %i[edit] do
        collection do
          post :show_music
        end
      end
      resources :creators, except: %i[edit]
    end
  end

  namespace :notices do
    resources :zakkuri_festival, only: %i[index]
  end
end

app/models/article.rb
require 'open-uri'

# == Schema Information
#
# Table name: articles
#
#  id                 :bigint           not null, primary key
#  image_url          :string
#  note               :text
#  title              :string           not null
#  uploaded_image_url :string
#  url                :string           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Article < ApplicationRecord
  include NicoUrlParser
  include UrlParser

  attr_writer :actor_ids, :music_ids

  has_many :actor_articles, -> { actor }, dependent: :destroy, inverse_of: :article, class_name: 'CreatorArticle'
  has_many :cinematographer_articles, -> { cinematographer }, dependent: :destroy, inverse_of: :article, class_name: 'CreatorArticle'
  has_many :editor_articles, -> { editor }, dependent: :destroy, inverse_of: :article, class_name: 'CreatorArticle'
  has_many :music_articles, dependent: :destroy, inverse_of: :article
  has_many :impressions, dependent: :destroy, inverse_of: :article
  has_many :published_impressions, -> { published }, class_name: 'Impression'
  has_many :published_tags, through: :published_impressions, source: :tags, class_name: 'Tag'

  validates :title, presence: true
  validates :url, presence: true

  after_save :set_actors!
  after_save :set_musics!

  scope :keyword_like, ->(keyword) { title_like(keyword).or(creator_name_like(keyword)) }
  scope :title_like, ->(title) { where("title ILIKE :title", title: "%#{title}%") }
  scope :creator_name_like, lambda { |name|
    sql = <<~SQL
      EXISTS (
            SELECT 1 
              FROM creators
        INNER JOIN creator_articles
                ON creators.id = creator_articles.creator_id
             WHERE creators.name ILIKE :name
               AND creator_articles.article_id = articles.id
      )
    SQL
    where(sanitize_sql_array([sql, { name: "%#{name}%" }]))
  }
  scope :has_published_impressions, lambda {
    sql = <<~SQL
      EXISTS (
            SELECT 1 
              FROM impressions
             WHERE impressions.article_id = articles.id
               AND impressions.status = :status
      )
    SQL
    where(sanitize_sql_array([sql, { status: Impression.statuses[:published] }]))
  }

  def self.find_or_initialize_by_url(url)
    article = _find_by_url(url)
    return article if article.present?

    _find_or_initialize_by_url(url) do |article, parsed|
      article.title = article.title.presence || parsed.css('meta[property="og:title"]').attribute('content').value
      article.image_url = article.image_url.presence || parsed.css('meta[property="og:image"]').attribute('content').value
    end
  end

  def reset_from_url
    html = URI.open(self.url).read
    parsed = Nokogiri.parse(html)
    self.title = parsed.css('meta[property="og:title"]').attribute('content').value
    self.image_url = parsed.css('meta[property="og:image"]').attribute('content').value
  end

  def set_actors!
    @actor_ids ||= actor_articles.pluck(:creator_id)
    transaction do
      exist_ids = actor_articles.pluck(:creator_id)
      actor_articles.reject { |actor_article| @actor_ids.include? actor_article.creator_id }.each(&:destroy!)
      @actor_ids.reject { |actor_id| exist_ids.include? actor_id }.each { |actor_id| actor_articles.create!(creator_id: actor_id) }
    end
  end

  def set_musics!
    @music_ids ||= music_articles.pluck(:music_id)
    transaction do
      exist_ids = music_articles.pluck(:music_id)
      music_articles.reject { |music_article| @music_ids.include? music_article.music_id }.each(&:destroy!)
      @music_ids.reject { |music_id| exist_ids.include? music_id }.each { |music_id| music_articles.create!(music_id: music_id) }
    end
  end

  class << self
    private def _find_by_url(url)
      url = nico_url(url) if nico?(url)
      Article.find_by(url: url)
    end

    private def nico_url(url)
      "https://www.nicovideo.jp/watch/#{nico_code(url)}"
    end
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < ApplicationController
    before_action :set_article, only: %i[show edit update destroy reset]

    def index
      @articles = Article.order(id: :desc).preload(actor_articles: :creator, music_articles: :music).page(params[:page])
    end

    def show; end

    def edit; end

    def update
      @article.attributes = article_params
      if @article.save
        Rails.cache.clear
        redirect_to admin_article_url(@article), notice: "Article was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def reset
      @article.reset_from_url
      render action: :edit
    end

    private
      def set_article
        @article = Article.preload(actor_articles: :creator, music_articles: :music).find(params[:id])
      end

      def article_params
        params.require(:article).permit(:note, :title, :url, :image_url, actor_ids: [], music_ids: [])
      end
  end
end

app/controllers/creators/articles_controller.rb
module Creators
  class ArticlesController < ApplicationController
    before_action :set_creator

    def show
      @article = @creator.articles.find(params[:id])
      @impressions = @article.published_impressions
    end

    private def set_creator
      @creator = Creator.find(params[:creator_id])
    end
  end
end

app/views/admin/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <div class="row m-2" >
    <div class="col-1 fw-bold">タイトル</div>
    <div class="col-10">
      <%= link_to article.title, article.url, target: :_blank %>
    </div>
  </div>
  <div class="row m-2" >
    <div class="col-1 fw-bold">アクター</div>
    <div class="col-10">
      <ul>
        <% article.actor_articles.each do |actor_article| %>
          <li><%= link_to actor_article.creator_name, admin_creator_path(id: actor_article.creator_id) %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row m-2" >
    <div class="col-1 fw-bold">音楽</div>
    <div class="col-10">
      <ul>
        <% article.music_articles.each do |music_article| %>
          <li><%= link_to music_article.music_title, admin_music_path(id: music_article.music_id) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/admin/articles/_form.html.erb
<%= form_with(model: [:admin, article]) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, 'タイトル', class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :url, 'URL', class: 'form-label' %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :image_url, '画像URL', class: 'form-label' %>
    <%= form.text_field :image_url, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :actor_list, 'アクター', class: 'form-label' %>
    <%= link_to "一覧", admin_shared_creators_path(relation_name: 'actor'), class: "btn btn-sm btn-outline-primary me-2", data: { turbo_frame: "modal" } %>
    <ul>
      <%= turbo_frame_tag "actor-id-field" do %>
        <%= render partial: 'admin/shared/creators/creator', collection: article.actor_articles.map(&:creator), locals: { relation_name: 'actor' } %>
      <% end %>
    </ul>
  </div>

  <div>
    <%= form.label :music_list, '音楽', class: 'form-label' %>
    <%= link_to "一覧", admin_shared_musics_path, class: "btn btn-sm btn-outline-primary me-2", data: { turbo_frame: "modal" } %>
    <ul>
      <%= turbo_frame_tag "music-id-field" do %>
        <%= render partial: 'admin/shared/musics/music', collection: article.music_articles.map(&:music) %>
      <% end %>
    </ul>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= turbo_frame_tag "modal" %>

app/views/admin/articles/edit.html.erb
<h1>Editing article</h1>

<%= link_to @article.title, @article.url, target: :_blank %>

<%= render partial: 'form', locals: { article: @article } %>

<br>

<div>
  <%= link_to "再取得", reset_admin_article_path %>
  <%= link_to "Show this article", admin_article_path(@article) %> |
  <%= link_to "Back to articles", admin_articles_path %>
</div>

app/views/admin/articles/index.html.erb
<div class="container" >
  <h3>Articles</h3>

  <div id="articles">
    <% @articles.each do |article| %>
      <div class="row py-3 border" id="<%= dom_id article %>">
        <div class="col-3">
          <%= link_to article.title, admin_article_path(article), class: 'link-dark' %>
        </div>
        <div class="col-3">
          <ul>
            <% article.actor_articles.each do |actor_article| %>
              <li>
                <%= actor_article.creator.name %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="col-3">
          <ul>
            <% article.music_articles.each do |music_article| %>
              <li>
                <%= music_article.music.title %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex border" >
    <%= paginate @articles %>
  </div>
</div>

app/views/admin/articles/new.html.erb
<h1>New article</h1>

<%= render partial: 'form', locals: { article: @article } %>

<br>

<div>
  <%= link_to "Back to articles", admin_articles_path %>
</div>

app/views/admin/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_admin_article_path(@article) %> |
  <%= link_to "Back to articles", admin_articles_path %>
</div>