config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "impressions#index"

  devise_scope :user do
    patch 'users/switch_show_name', to: 'users/registrations#switch_show_name'
    get 'users/two_factor_auth', to: 'users/sessions#two_factor_auth'
  end

  resources :creators, only: %i[index show] do
    resources :articles, only: %i[show], module: :creators
  end
  namespace :impressions do
    resources :tags, only: %i[index update destroy]
  end
  resources :impressions, only: %i[index show]
  resources :articles, only: %i[show]

  namespace :my_page do
    resources :impressions do
      collection do
        post :update_article
        get :download
      end
      member do
        patch :publish
        post :post_mastodon
      end
    end
    resources :impression_tags, only: %i[index new create destroy] do
      collection do
        post :show_all_tags
        post :add_tag
      end
    end
    resources :two_step_verifications, only: %i[new create]
    resources :tag_groups do
      member do
        get :edit_tags
        post :add_tag
        delete :destroy_tag
      end
    end
  end

  namespace :admin do
    resources :users
    resources :articles, only: %i[index show edit update] do
      member do
        get :reset
      end
    end
    resources :impressions, only: %i[index show destroy]
    resources :musics, except: :destroy
    resources :creators, except: :destroy
    resource :mastodon_data_linkage do
      collection do
        get :callback
      end
    end

    namespace :shared do
      resources :musics, except: %i[edit] do
        collection do
          post :show_music
        end
      end
      resources :creators, except: %i[edit]
    end
  end

  namespace :notices do
    resources :zakkuri_festival, only: %i[index]
  end
end

app/models/creator.rb
# == Schema Information
#
# Table name: creators
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  note       :text
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Creator < ApplicationRecord
  include NicoUrlParser
  include UrlParser

  has_many :creator_articles, dependent: :destroy, inverse_of: :creator
  has_many :articles, through: :creator_articles
  has_many :music_creators, dependent: :destroy, inverse_of: :creator
  has_many :musics, through: :music_creators

  validates :name, presence: true

  scope :order_by_name, -> { order(:name) }
  scope :name_like, ->(keyword) { where("name ILIKE :keyword", keyword: "%#{keyword}%") }
  scope :has_published_impressions, lambda {
    sql = <<~SQL
      EXISTS (
            SELECT 1 
              FROM creator_articles
        INNER JOIN impressions
                ON creator_articles.article_id = impressions.article_id
               AND impressions.status = :status 
             WHERE creators.id = creator_articles.creator_id
      )
    SQL
    where(sanitize_sql_array([sql, { status: Impression.statuses[:published] }]))
  }

  def self.find_or_initialize_by_url(url)
    record = _find_by_url(url)
    return record if record.present?

    _find_or_initialize_by_url(url) do |creator, parsed|
      creator.name = creator.name.presence || parsed.css('meta[property="profile:username"]').attribute('content').value
    end
  end

  class << self
    private def _find_by_url(url)
      url = nico_url(url) if nico?(url)
      Creator.find_by(url: url)
    end

    private def nico_url(url)
      "https://www.nicovideo.jp/user/#{nico_code(url)}"
    end
  end
end

app/models/music.rb
# == Schema Information
#
# Table name: musics
#
#  id         :bigint           not null, primary key
#  image_url  :string
#  note       :text
#  title      :string           not null
#  url        :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Music < ApplicationRecord
  include NicoUrlParser
  include UrlParser

  has_many :music_articles, dependent: :destroy, inverse_of: :music
  has_many :articles, inverse_of: :musics
  has_many :music_creators, dependent: :destroy, inverse_of: :music
  has_many :creators, inverse_of: :musics

  validates :title, presence: true
  validates :url, presence: true

  scope :title_like, ->(keyword) { where("title ILIKE :keyword", keyword: "%#{keyword}%") }

  def self.by_url(url)
    if nico?(url)
      self.where(url: nico_url(url))
    else
      _by_url(url)
    end
  end

  def self.find_or_initialize_by_url(url)
    music = _find_by_url(url)
    return music if music.present?

    _find_or_initialize_by_url(url) do |music, parsed|
      music.title = music.title.presence || parsed.css('meta[property="og:title"]').attribute('content').value
      music.image_url = music.image_url.presence || parsed.css('meta[property="og:image"]').attribute('content').value
    end
  end

  class << self
    private def _find_by_url(url)
      url = nico_url(url) if nico?(url)
      Music.find_by(url: url)
    end

    private def nico_url(url)
      "https://www.nicovideo.jp/watch/#{nico_code(url)}"
    end
  end
end

app/controllers/admin/musics_controller.rb
module Admin
  class MusicsController < ApplicationController
    before_action :set_music, only: %i[show edit update destroy]

    def index
      @musics = Music.all
      @musics = @musics.title_like(search_params[:keyword]) if search_params[:keyword].present?
      @musics = @musics.page(params[:page])
    end

    def new
      @music = Music.new
    end

    def show
    end

    def edit; end

    def update
      @music.attributes = music_params
      if @music.save
        redirect_to admin_music_url(@music), notice: "Music was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def create
      @music = Music.new(music_params)
      if @music.save
        redirect_to admin_music_url(@music), notice: "Music was successfully updated."
      else
        render :new, status: :unprocessable_entity
      end
    end

    private
      def set_music
        @music = Music.find(params[:id])
      end

      def music_params
        params.require(:music).permit(:note, :title, :url)
      end

      def search_params
        params.fetch(:search, {}).permit(:keyword)
      end
  end
end

app/controllers/admin/shared/creators_controller.rb
module Admin
  module Shared
    class CreatorsController < ApplicationController
      before_action :set_creator, only: %i[update destroy]

      def index
        @creators = Creator.order_by_name
        @creators = @creators.where("name LIKE :name", name: "%#{search_params[:name]}%")
        @creators = @creators.page(params[:page])
      end

      def new
        @creator = Creator.new
      end

      def create
        @creator = Creator.new(creator_params)
        render :new, status: :unprocessable_entity unless @creator.save
      end

      def update; end

      def destroy; end

      private
        def creator_params
          params.require(:creator).permit(:name, :url)
        end

        def search_params
          params.fetch(:search, {}).permit(:name)
        end

        def set_creator
          @creator = Creator.find(params[:id])
        end
    end
  end
end

app/controllers/admin/shared/musics_controller.rb
module Admin
  module Shared
    class MusicsController < ApplicationController
      before_action :set_music, only: %i[update destroy]

      def index
        @musics = Music.all
        @musics = @musics.by_url(search_params[:url]) if search_params[:url].present?
        @musics = @musics.where("title LIKE :title", title: "%#{search_params[:title]}%")
        @musics = @musics.page(params[:page])
      end

      def new
        @music = Music.new
      end

      def create
        @music = Music.new(music_params)
        render :new, status: :unprocessable_entity unless @music.save
      end

      def show; end

      def destroy; end

      def show_music
        @music = Music.find_or_initialize_by_url(params[:url])
      end

      private def music_params
        params.require(:music).permit(:title, :url)
      end

      private def search_params
        params.fetch(:search, {}).permit(:title, :url)
      end

      private def set_music
        @music = Music.find(params[:id])
      end
    end
  end
end

app/views/admin/shared/musics/_form.html.erb
<%= form_with(url: admin_shared_musics_path, model: music, data: { action: "turbo:submit-end->modal#close" }, method: :post) do |form| %>
  <% if music.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
        <% music.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, 'タイトル', class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
    <%= form.hidden_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/shared/musics/_music.html.erb
<li id="<%= dom_id music %>">
  <% if music.present? %>
    <%= music.title %>
    <%= hidden_field(:article, "music_ids", value: music.id, multiple: true) %>
    <%= link_to '削除', admin_shared_music_path(music), data: { turbo_method: :delete } %>
  <% end %>
</li>

app/views/admin/shared/musics/create.turbo_stream.erb
<%= turbo_stream.append "music-id-field", partial: 'music', locals: { music: @music } %>

app/views/admin/shared/musics/destroy.turbo_stream.erb
<%= turbo_stream.remove @music %>

app/views/admin/shared/musics/index.html.erb
<%= render "multiple_select_modal", title: "musics" do %>
  <div class="container">
    <h3>Musics</h3>

    <div class='mb-3'>
      <%= form_with(url: admin_shared_musics_path, scope: :search, method: :get, html: {
        data: {
          turbo_frame: "music-list",
          controller: "form",
          action: "input->form#submit"
        }
      }) do |form| %>
        <div class="row m-2">
          <div class="col-12">
            <%= form.label :url, 'URL', class: 'form-label' %>
            <%= form.text_field :url, class: 'form-control' %>
          </div>
        </div>
        <div class="row m-2">
          <div class="col-12">
            <%= form.label :title, 'タイトル', class: 'form-label' %>
            <%= form.text_field :title, class: 'form-control' %>
          </div>
        </div>
      <% end %>
    </div>

    <%= turbo_frame_tag "music-list" do %>
      <div id="musics">
        <div class="row py-3 border">
          <div class="col-11">名前</div>
          <div class="col-1">
            <%= link_to '新規', new_admin_shared_music_path, class: 'link-dark', data: { turbo_frame: "modal" } %>
          </div>
        </div>
        <% @musics.each do |music| %>
          <div class="row py-3 border" id="<%= dom_id music %>">
            <div class="col-12">
              <%= link_to music.title, admin_shared_music_path(music), class: "link-dark", data: { turbo_method: :patch } %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="d-flex border" >
        <%= paginate @musics %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/shared/musics/new.html.erb
<%= render "modal", title: "Musics" do %>
  <h1>New music</h1>
  <%= form_with(url: show_music_admin_shared_musics_path, method: :post, html: {
    data: {
      controller: "form",
      action: "input->form#submit"
    }
  }) do |form| %>
    <%= form.label :url, 'URL', class: 'form-label' %>
    <%= form.text_field :url, class: 'form-control' %>
  <% end %>

  <div id="music-field">
    <%= render partial: 'form', locals: { music: @music } %>
  </div>

  <br>

  <div>
    <%= link_to "Back to musics", admin_shared_musics_path %>
  </div>
<% end %>

app/views/admin/shared/musics/show_music.turbo_stream.erb
<%= turbo_stream.update 'music-field', partial: 'form', locals: { music: @music } %>

app/views/admin/shared/musics/update.turbo_stream.erb
<%= turbo_stream.append "music-id-field", partial: 'music', locals: { music: @music } %>