config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "impressions#index"

  devise_scope :user do
    patch 'users/switch_show_name', to: 'users/registrations#switch_show_name'
    get 'users/two_factor_auth', to: 'users/sessions#two_factor_auth'
  end

  resources :creators, only: %i[index show] do
    resources :articles, only: %i[show], module: :creators
  end
  namespace :impressions do
    resources :tags, only: %i[index update destroy]
  end
  resources :impressions, only: %i[index show]
  resources :articles, only: %i[show]

  namespace :my_page do
    resources :impressions do
      collection do
        post :update_article
        get :download
      end
      member do
        patch :publish
        post :post_mastodon
      end
    end
    resources :impression_tags, only: %i[index new create destroy] do
      collection do
        post :show_all_tags
        post :add_tag
      end
    end
    resources :two_step_verifications, only: %i[new create]
    resources :tag_groups do
      member do
        get :edit_tags
        post :add_tag
        delete :destroy_tag
      end
    end
  end

  namespace :admin do
    resources :users
    resources :articles, only: %i[index show edit update] do
      member do
        get :reset
      end
    end
    resources :impressions, only: %i[index show destroy]
    resources :musics, except: :destroy
    resources :creators, except: :destroy
    resource :mastodon_data_linkage do
      collection do
        get :callback
      end
    end

    namespace :shared do
      resources :musics, except: %i[edit] do
        collection do
          post :show_music
        end
      end
      resources :creators, except: %i[edit]
    end
  end

  namespace :notices do
    resources :zakkuri_festival, only: %i[index]
  end
end

app/controllers/admin/shared/creators_controller.rb
module Admin
  module Shared
    class CreatorsController < ApplicationController
      before_action :set_creator, only: %i[update destroy]

      def index
        @creators = Creator.order_by_name
        @creators = @creators.where("name LIKE :name", name: "%#{search_params[:name]}%")
        @creators = @creators.page(params[:page])
      end

      def new
        @creator = Creator.new
      end

      def create
        @creator = Creator.new(creator_params)
        render :new, status: :unprocessable_entity unless @creator.save
      end

      def update; end

      def destroy; end

      private
        def creator_params
          params.require(:creator).permit(:name, :url)
        end

        def search_params
          params.fetch(:search, {}).permit(:name)
        end

        def set_creator
          @creator = Creator.find(params[:id])
        end
    end
  end
end

app/controllers/admin/shared/musics_controller.rb
module Admin
  module Shared
    class MusicsController < ApplicationController
      before_action :set_music, only: %i[update destroy]

      def index
        @musics = Music.all
        @musics = @musics.by_url(search_params[:url]) if search_params[:url].present?
        @musics = @musics.where("title LIKE :title", title: "%#{search_params[:title]}%")
        @musics = @musics.page(params[:page])
      end

      def new
        @music = Music.new
      end

      def create
        @music = Music.new(music_params)
        render :new, status: :unprocessable_entity unless @music.save
      end

      def show; end

      def destroy; end

      def show_music
        @music = Music.find_or_initialize_by_url(params[:url])
      end

      private def music_params
        params.require(:music).permit(:title, :url)
      end

      private def search_params
        params.fetch(:search, {}).permit(:title, :url)
      end

      private def set_music
        @music = Music.find(params[:id])
      end
    end
  end
end

app/views/shared/_article_image.html.erb
<% cache "article_image_#{article.id}", expires_in: 3600 * 24 * 3 do %>
  <%= image_tag(article.image_url) %>
<% end %>

app/views/shared/_header.html.erb
<div class="container sticky-top bg-white">
  <header class="d-flex flex-wrap align-items-center justify-content-between justify-content-md-between py-2 mb-2 border-bottom">
    <ul class="nav mb-2 mb-md-0">
      <li><%= link_to "トップ", root_path, class: "nav-link px-2 link-secondary" %></li>
      <li><%= link_to "踊り手別", creators_path, class: "nav-link px-2 link-secondary" %></li>
      <% if current_user.present? %>
        <li>
          <div class="dropdown">
            <%= link_to '書く', '#', class: 'nav-link px-2 link-secondary dropdown-toggle', id: 'dropdownWriteLink', data: { bs_toggle: 'dropdown' } %>
            <ul class="dropdown-menu" aria-labelledby="dropdownWriteLink">
              <li><%= link_to "感想を書く", new_my_page_impression_path, class: "dropdown-item" %></li>
              <li><%= link_to "下書き一覧", my_page_impressions_path(status: :pending), class: "dropdown-item" %></li>
              <li><%= link_to "公開中一覧", my_page_impressions_path(status: :published), class: "dropdown-item" %></li>
              <li><%= link_to "タグ分類", my_page_tag_groups_path, class: "dropdown-item" %></li>
            </ul>
          </div>
        </li>
        <% if current_user.enable_admin? %>
          <li>
            <div class="dropdown">
              <%= link_to 'マスタ', '#', class: 'nav-link px-2 link-secondary dropdown-toggle', id: 'dropdownMasterLink', data: { bs_toggle: 'dropdown' } %>
              <ul class="dropdown-menu" aria-labelledby="dropdownMasterLink">
                <li><%= link_to "作品", admin_articles_path, class: "dropdown-item" %></li>
                <li><%= link_to "クリエイター", admin_creators_path, class: "dropdown-item" %></li>
                <li><%= link_to "楽曲", admin_musics_path, class: "dropdown-item" %></li>
                <li><%= link_to "ユーザー", admin_users_path, class: "dropdown-item" %></li>
                <li><%= link_to "感想", admin_impressions_path, class: "dropdown-item" %></li>
                <li><%= link_to "マストドン連携", admin_mastodon_data_linkage_path, class: "dropdown-item" %></li>
              </ul>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <div class="text-end">
      <% if current_user.present? %>
        <%= render partial: "shared/user_menu" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-outline-primary me-2' %>
      <% end %>
    </div>
  </header>
</div>

app/views/shared/_user_menu.html.erb
<%= turbo_frame_tag "user-dropdown-menu", class: 'dropdown' do %>
  <%= link_to current_user.name, '#', class: 'btn btn-secondary dropdown-toggle', role: 'button', id: 'dropdownMenuLink', data: { bs_toggle: 'dropdown' } %>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <li>
      <%= link_to 'ユーザー情報編集', edit_user_registration_path, class: 'dropdown-item' %>
    </li>
    <li>
      <% if current_user.show_name? %>
        <%= link_to '感想に名前を表示しないようにする', users_switch_show_name_path, class: 'dropdown-item', data: { turbo_method: :patch } %>
      <% else %>
        <%= link_to '感想に名前を表示するようにする', users_switch_show_name_path, class: 'dropdown-item', data: { turbo_frame: 'user-dropdown-menu', turbo_method: :patch } %>
      <% end %>
    </li>
    <li>
      <%= link_to 'ログアウト', destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
    </li>
  </ul>
<% end %>